root: true
env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - standard-with-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/comma-dangle': ['error', 'always-multiline']
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/naming-convention':
      - 'error'
      - selector: 'interface'
        format:
          - 'PascalCase'
      - selector: 'typeAlias'
        format:
          - 'PascalCase'
ignorePatterns:
  - dist
